-- ==========================================
-- Identity Column
-- ==========================================

/*
Definition:
An Identity Column automatically
generates values for a column
when new rows are inserted.
*/

-- ==========================================
-- GENERATED ALWAYS
-- ==========================================

CREATE TABLE students
(
    student_id INTEGER
    GENERATED ALWAYS AS IDENTITY
    PRIMARY KEY,

    student_name VARCHAR(100),
    age INTEGER
);

------------------------------------------------

INSERT INTO students(student_name,age)
VALUES
('Ali',20),
('Sara',21),
('Ahmed',22);

------------------------------------------------

SELECT *
FROM students;

------------------------------------------------

-- GENERATED BY DEFAULT

CREATE TABLE employees
(
    employee_id INTEGER
    GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,

    employee_name VARCHAR(100)
);

------------------------------------------------

INSERT INTO employees(employee_name)
VALUES ('Ali');

------------------------------------------------

INSERT INTO employees(employee_id,employee_name)
VALUES (100,'Sara');

------------------------------------------------

SELECT *
FROM employees;

------------------------------------------------

-- Interview Questions

/*
Q1. What is an Identity Column?

Answer:
An Identity Column automatically
generates values for a column.

----------------------------------------

Q2. Difference between
GENERATED ALWAYS and
GENERATED BY DEFAULT?

ALWAYS
-------
Database always generates the value.

BY DEFAULT
----------
Database generates the value only if
you don't provide one.

----------------------------------------

Q3. Difference between
SERIAL and IDENTITY?

SERIAL:
Older PostgreSQL feature.

IDENTITY:
SQL Standard and recommended.
*/